# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
# config/database.yml
default: &default
  adapter: mysql2
  database: test_db
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root
  host: localhost

development:
  <<: *default
  database: test_db

test:
  <<: *default
  database: your_app_test

production:
  <<: *default
  database: your_app_production
